name: dart_course

description: A sample command-line application.

version: 1.0.0

# repository: https://github.com/my_org/my_repo
# homepage: https://github.com/my_org/my_repo
# issue_tracker: https://github.com/my_org/my_repo
# documentation: https://github.com/my_org/my_repo
# publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  dio: ^5.9.0
  equatable: ^2.0.7
  http: ^1.6.0
  meta: ^1.17.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# dependency_overrides: 
#   analyzer: ^9.0.0

executables: 
  dartcourse:
